package edu.uci.ics.gmehta1.service.billing.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.uci.ics.gmehta1.service.billing.core.Amount;
@JsonIgnoreProperties(value = "details") // Tells Jackson to ignore dataValid field generated by DataValidation interface
public class AmountModel {
    private String total;
    private String currency;

    @JsonCreator
    public AmountModel(@JsonProperty(value = "total", required = true) String total,
                       @JsonProperty(value = "currency", required = true) String currency) {
        this.total = total;
        this.currency = currency;
    }

    public static AmountModel buildModelFromObject(Amount a) {
        return new AmountModel(a.getTotal(),a.getCurrency());
    }
    public String getTotal() {
        return total;
    }

    public String getCurrency() {
        return currency;
    }
}
